services:
  dev-env:
    build:
      context: '.'
      dockerfile: Dockerfile.release
      args:
        USER_ID: '${USER_ID:-1000}'
        GROUP_ID: '${GROUP_ID:-1000}'

    user: dev-user
    container_name: dev-env
    volumes:
      - '$HOME/.dev/dev-environment:/home/dev-user/dev-environment'
      - '$HOME/.dev-user-config:/home/dev-user/.dev-user-config'

    environment:
      - NODE_ENV=development

    ports:
      - '9229:9229'

    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash", "-c", "if entrypoint; then bash; else exit 1; fi"]
